# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  cosmosapi:
    image: cosmosapi
    build:
      context: .
      dockerfile: CosmosApi/Dockerfile
    ports:
      - 8080:8080
